/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppJournalRouteImport } from './routes/app/journal'
import { Route as AppPlaybooksRouteImport } from './routes/app/playbooks'
import { Route as AppPropRulesRouteImport } from './routes/app/prop-rules'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppReviewsRouteImport } from './routes/app/reviews'
import { Route as AppRiskCalculatorRouteImport } from './routes/app/risk-calculator'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as AppJournalTradeIdRouteImport } from './routes/app/journal/$tradeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybooksRoute = AppPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AppRoute,
} as any)
const AppPropRulesRoute = AppPropRulesRouteImport.update({
  id: '/prop-rules',
  path: '/prop-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskCalculatorRoute = AppRiskCalculatorRouteImport.update({
  id: '/risk-calculator',
  path: '/risk-calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJournalTradeIdRoute = AppJournalTradeIdRouteImport.update({
  id: '/$tradeId',
  path: '/$tradeId',
  getParentRoute: () => AppJournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/prop-rules': typeof AppPropRulesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk-calculator': typeof AppRiskCalculatorRoute
  '/app/settings': typeof AppSettingsRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/journal/$tradeId': typeof AppJournalTradeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/prop-rules': typeof AppPropRulesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk-calculator': typeof AppRiskCalculatorRoute
  '/app/settings': typeof AppSettingsRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/app/journal/$tradeId': typeof AppJournalTradeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/journal': typeof AppJournalRouteWithChildren
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/prop-rules': typeof AppPropRulesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/risk-calculator': typeof AppRiskCalculatorRoute
  '/app/settings': typeof AppSettingsRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/journal/$tradeId': typeof AppJournalTradeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/app/analytics'
    | '/app/journal'
    | '/app/playbooks'
    | '/app/prop-rules'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk-calculator'
    | '/app/settings'
    | '/share/$token'
    | '/app/'
    | '/app/journal/$tradeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/app/analytics'
    | '/app/journal'
    | '/app/playbooks'
    | '/app/prop-rules'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk-calculator'
    | '/app/settings'
    | '/share/$token'
    | '/app'
    | '/app/journal/$tradeId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/app/analytics'
    | '/app/journal'
    | '/app/playbooks'
    | '/app/prop-rules'
    | '/app/reports'
    | '/app/reviews'
    | '/app/risk-calculator'
    | '/app/settings'
    | '/share/$token'
    | '/app/'
    | '/app/journal/$tradeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playbooks': {
      id: '/app/playbooks'
      path: '/playbooks'
      fullPath: '/app/playbooks'
      preLoaderRoute: typeof AppPlaybooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prop-rules': {
      id: '/app/prop-rules'
      path: '/prop-rules'
      fullPath: '/app/prop-rules'
      preLoaderRoute: typeof AppPropRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk-calculator': {
      id: '/app/risk-calculator'
      path: '/risk-calculator'
      fullPath: '/app/risk-calculator'
      preLoaderRoute: typeof AppRiskCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/journal/$tradeId': {
      id: '/app/journal/$tradeId'
      path: '/$tradeId'
      fullPath: '/app/journal/$tradeId'
      preLoaderRoute: typeof AppJournalTradeIdRouteImport
      parentRoute: typeof AppJournalRoute
    }
  }
}

interface AppJournalRouteChildren {
  AppJournalTradeIdRoute: typeof AppJournalTradeIdRoute
}

const AppJournalRouteChildren: AppJournalRouteChildren = {
  AppJournalTradeIdRoute: AppJournalTradeIdRoute,
}

const AppJournalRouteWithChildren = AppJournalRoute._addFileChildren(
  AppJournalRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppJournalRoute: typeof AppJournalRouteWithChildren
  AppPlaybooksRoute: typeof AppPlaybooksRoute
  AppPropRulesRoute: typeof AppPropRulesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppRiskCalculatorRoute: typeof AppRiskCalculatorRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppJournalRoute: AppJournalRouteWithChildren,
  AppPlaybooksRoute: AppPlaybooksRoute,
  AppPropRulesRoute: AppPropRulesRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppRiskCalculatorRoute: AppRiskCalculatorRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
