// Supabase database types. Originally generated by `supabase gen types`, but
// entries for playbooks, playbook_checklist_items, playbook_attachments,
// trade_ideas, trade_reviews, period_reviews, prop_firm_rules,
// prop_firm_rule_events, coach_shares, coach_comments, accounts, and the
// added columns on trades (playbook_id, playbook_snapshot, confidence,
// account_id, trade_group_id), prop_firm_rules/prop_firm_rule_events
// (account_id), and coach_shares (account_id) were added by hand to match
// the migrations in supabase/migrations/, since generating fresh types
// requires a live connection to the actual Supabase project. If you have the
// Supabase CLI linked to the project, running `supabase gen types
// typescript --linked > src/integrations/supabase/types.ts` will regenerate
// this file from the real schema and should produce an equivalent (or more
// current, if the migrations have moved on) result.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      accounts: {
        Row: {
          account_type: string
          base_currency: string
          broker: string | null
          created_at: string
          default_risk_percent: number
          id: string
          is_active: boolean
          is_archived: boolean
          name: string
          owner_id: string
          portfolio_id: string
          starting_equity: number
          updated_at: string
        }
        Insert: {
          account_type?: string
          base_currency?: string
          broker?: string | null
          created_at?: string
          default_risk_percent?: number
          id?: string
          is_active?: boolean
          is_archived?: boolean
          name: string
          owner_id: string
          portfolio_id: string
          starting_equity?: number
          updated_at?: string
        }
        Update: {
          account_type?: string
          base_currency?: string
          broker?: string | null
          created_at?: string
          default_risk_percent?: number
          id?: string
          is_active?: boolean
          is_archived?: boolean
          name?: string
          owner_id?: string
          starting_equity?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "accounts_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
        ]
      }
      coach_comments: {
        Row: {
          author_name: string
          body: string
          created_at: string
          id: string
          owner_id: string
          share_id: string
          trade_id: string | null
        }
        Insert: {
          author_name: string
          body: string
          created_at?: string
          id?: string
          owner_id: string
          share_id: string
          trade_id?: string | null
        }
        Update: {
          author_name?: string
          body?: string
          created_at?: string
          id?: string
          owner_id?: string
          share_id?: string
          trade_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "coach_comments_share_id_fkey"
            columns: ["share_id"]
            isOneToOne: false
            referencedRelation: "coach_shares"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coach_comments_trade_id_fkey"
            columns: ["trade_id"]
            isOneToOne: false
            referencedRelation: "trades"
            referencedColumns: ["id"]
          },
        ]
      }
      coach_shares: {
        Row: {
          account_id: string | null
          created_at: string
          expires_at: string | null
          hide_dollar_pnl: boolean
          id: string
          label: string
          last_viewed_at: string | null
          owner_id: string
          period_end: string | null
          period_start: string | null
          permission: string
          portfolio_id: string
          revoked_at: string | null
          token: string
          updated_at: string
          view_count: number
        }
        Insert: {
          account_id?: string | null
          created_at?: string
          expires_at?: string | null
          hide_dollar_pnl?: boolean
          id?: string
          label?: string
          last_viewed_at?: string | null
          owner_id: string
          period_end?: string | null
          period_start?: string | null
          permission?: string
          portfolio_id: string
          revoked_at?: string | null
          token: string
          updated_at?: string
          view_count?: number
        }
        Update: {
          account_id?: string | null
          created_at?: string
          expires_at?: string | null
          hide_dollar_pnl?: boolean
          id?: string
          label?: string
          last_viewed_at?: string | null
          owner_id?: string
          period_end?: string | null
          period_start?: string | null
          permission?: string
          portfolio_id?: string
          revoked_at?: string | null
          token?: string
          updated_at?: string
          view_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "coach_shares_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coach_shares_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
        ]
      }
      import_batches: {
        Row: {
          created_at: string
          file_name: string | null
          id: string
          imported_rows: number
          invalid_rows: number
          owner_id: string
          portfolio_id: string
          source: string
          status: string
          total_rows: number
          updated_at: string
          valid_rows: number
        }
        Insert: {
          created_at?: string
          file_name?: string | null
          id?: string
          imported_rows?: number
          invalid_rows?: number
          owner_id: string
          portfolio_id: string
          source: string
          status?: string
          total_rows?: number
          updated_at?: string
          valid_rows?: number
        }
        Update: {
          created_at?: string
          file_name?: string | null
          id?: string
          imported_rows?: number
          invalid_rows?: number
          owner_id?: string
          portfolio_id?: string
          source?: string
          status?: string
          total_rows?: number
          updated_at?: string
          valid_rows?: number
        }
        Relationships: [
          {
            foreignKeyName: "import_batches_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
        ]
      }
      import_rows: {
        Row: {
          batch_id: string
          created_at: string
          id: string
          normalized_data: Json | null
          owner_id: string
          raw_data: Json
          row_number: number
          source_trade_id: string | null
          status: string
          updated_at: string
          validation_errors: Json
        }
        Insert: {
          batch_id: string
          created_at?: string
          id?: string
          normalized_data?: Json | null
          owner_id: string
          raw_data?: Json
          row_number: number
          source_trade_id?: string | null
          status?: string
          updated_at?: string
          validation_errors?: Json
        }
        Update: {
          batch_id?: string
          created_at?: string
          id?: string
          normalized_data?: Json | null
          owner_id?: string
          raw_data?: Json
          row_number?: number
          source_trade_id?: string | null
          status?: string
          updated_at?: string
          validation_errors?: Json
        }
        Relationships: [
          {
            foreignKeyName: "import_rows_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "import_batches"
            referencedColumns: ["id"]
          },
        ]
      }
      period_reviews: {
        Row: {
          commitment: string | null
          created_at: string
          id: string
          owner_id: string
          period_end: string
          period_start: string
          period_type: string
          portfolio_id: string
          updated_at: string
        }
        Insert: {
          commitment?: string | null
          created_at?: string
          id?: string
          owner_id: string
          period_end: string
          period_start: string
          period_type: string
          portfolio_id: string
          updated_at?: string
        }
        Update: {
          commitment?: string | null
          created_at?: string
          id?: string
          owner_id?: string
          period_end?: string
          period_start?: string
          period_type?: string
          portfolio_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "period_reviews_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
        ]
      }
      playbook_attachments: {
        Row: {
          caption: string | null
          content_type: string | null
          created_at: string
          file_name: string | null
          id: string
          owner_id: string
          playbook_id: string
          storage_path: string
          updated_at: string
        }
        Insert: {
          caption?: string | null
          content_type?: string | null
          created_at?: string
          file_name?: string | null
          id?: string
          owner_id: string
          playbook_id: string
          storage_path: string
          updated_at?: string
        }
        Update: {
          caption?: string | null
          content_type?: string | null
          created_at?: string
          file_name?: string | null
          id?: string
          owner_id?: string
          playbook_id?: string
          storage_path?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "playbook_attachments_playbook_id_fkey"
            columns: ["playbook_id"]
            isOneToOne: false
            referencedRelation: "playbooks"
            referencedColumns: ["id"]
          },
        ]
      }
      playbook_checklist_items: {
        Row: {
          created_at: string
          id: string
          is_required: boolean
          order_index: number
          owner_id: string
          playbook_id: string
          prompt: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_required?: boolean
          order_index?: number
          owner_id: string
          playbook_id: string
          prompt: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_required?: boolean
          order_index?: number
          owner_id?: string
          playbook_id?: string
          prompt?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "playbook_checklist_items_playbook_id_fkey"
            columns: ["playbook_id"]
            isOneToOne: false
            referencedRelation: "playbooks"
            referencedColumns: ["id"]
          },
        ]
      }
      playbooks: {
        Row: {
          created_at: string
          description: string | null
          direction: string
          ideal_conditions: string | null
          id: string
          invalidation_rules: string | null
          market: string
          name: string
          owner_id: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          direction?: string
          ideal_conditions?: string | null
          id?: string
          invalidation_rules?: string | null
          market?: string
          name: string
          owner_id: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          direction?: string
          ideal_conditions?: string | null
          id?: string
          invalidation_rules?: string | null
          market?: string
          name?: string
          owner_id?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      portfolio_settings: {
        Row: {
          created_at: string
          default_risk_percent: number
          display_preferences: Json
          id: string
          portfolio_id: string
          preferred_sessions: string[]
          preferred_symbols: string[]
          updated_at: string
        }
        Insert: {
          created_at?: string
          default_risk_percent?: number
          display_preferences?: Json
          id?: string
          portfolio_id: string
          preferred_sessions?: string[]
          preferred_symbols?: string[]
          updated_at?: string
        }
        Update: {
          created_at?: string
          default_risk_percent?: number
          display_preferences?: Json
          id?: string
          portfolio_id?: string
          preferred_sessions?: string[]
          preferred_symbols?: string[]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "portfolio_settings_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: true
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
        ]
      }
      portfolios: {
        Row: {
          account_type: string
          base_currency: string
          created_at: string
          current_equity: number
          id: string
          is_active: boolean
          name: string
          owner_id: string
          starting_equity: number
          updated_at: string
        }
        Insert: {
          account_type?: string
          base_currency?: string
          created_at?: string
          current_equity?: number
          id?: string
          is_active?: boolean
          name: string
          owner_id: string
          starting_equity?: number
          updated_at?: string
        }
        Update: {
          account_type?: string
          base_currency?: string
          created_at?: string
          current_equity?: number
          id?: string
          is_active?: boolean
          name?: string
          owner_id?: string
          starting_equity?: number
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          base_currency: string
          created_at: string
          display_name: string | null
          id: string
          onboarding_completed: boolean
          timezone: string
          trader_type: string
          updated_at: string
          user_id: string
        }
        Insert: {
          base_currency?: string
          created_at?: string
          display_name?: string | null
          id?: string
          onboarding_completed?: boolean
          timezone?: string
          trader_type?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          base_currency?: string
          created_at?: string
          display_name?: string | null
          id?: string
          onboarding_completed?: boolean
          timezone?: string
          trader_type?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      prop_firm_rule_events: {
        Row: {
          account_id: string
          created_at: string
          event_type: string
          id: string
          message: string
          occurred_on: string
          owner_id: string
          severity: string
          trade_id: string | null
        }
        Insert: {
          account_id: string
          created_at?: string
          event_type: string
          id?: string
          message: string
          occurred_on: string
          owner_id: string
          severity: string
          trade_id?: string | null
        }
        Update: {
          account_id?: string
          created_at?: string
          event_type?: string
          id?: string
          message?: string
          occurred_on?: string
          owner_id?: string
          severity?: string
          trade_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "prop_firm_rule_events_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "prop_firm_rule_events_trade_id_fkey"
            columns: ["trade_id"]
            isOneToOne: false
            referencedRelation: "trades"
            referencedColumns: ["id"]
          },
        ]
      }
      prop_firm_rules: {
        Row: {
          account_id: string
          allow_news_trading: boolean
          allow_weekend_holding: boolean
          calculation_basis: string
          consistency_percent: number | null
          created_at: string
          id: string
          is_active: boolean
          max_daily_loss_percent: number
          max_total_drawdown_percent: number
          max_trading_days: number | null
          min_trading_days: number | null
          notes: string | null
          owner_id: string
          profit_target_percent: number | null
          timezone: string
          updated_at: string
        }
        Insert: {
          account_id: string
          allow_news_trading?: boolean
          allow_weekend_holding?: boolean
          calculation_basis?: string
          consistency_percent?: number | null
          created_at?: string
          id?: string
          is_active?: boolean
          max_daily_loss_percent: number
          max_total_drawdown_percent: number
          max_trading_days?: number | null
          min_trading_days?: number | null
          notes?: string | null
          owner_id: string
          profit_target_percent?: number | null
          timezone?: string
          updated_at?: string
        }
        Update: {
          account_id?: string
          allow_news_trading?: boolean
          allow_weekend_holding?: boolean
          calculation_basis?: string
          consistency_percent?: number | null
          created_at?: string
          id?: string
          is_active?: boolean
          max_daily_loss_percent?: number
          max_total_drawdown_percent?: number
          max_trading_days?: number | null
          min_trading_days?: number | null
          notes?: string | null
          owner_id?: string
          profit_target_percent?: number | null
          timezone?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "prop_firm_rules_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: true
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      tags: {
        Row: {
          category: string
          created_at: string
          id: string
          name: string
          owner_id: string
          slug: string
          updated_at: string
        }
        Insert: {
          category?: string
          created_at?: string
          id?: string
          name: string
          owner_id: string
          slug: string
          updated_at?: string
        }
        Update: {
          category?: string
          created_at?: string
          id?: string
          name?: string
          owner_id?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      trade_attachments: {
        Row: {
          caption: string | null
          content_type: string | null
          created_at: string
          file_name: string | null
          id: string
          owner_id: string
          storage_path: string
          trade_id: string
          updated_at: string
        }
        Insert: {
          caption?: string | null
          content_type?: string | null
          created_at?: string
          file_name?: string | null
          id?: string
          owner_id: string
          storage_path: string
          trade_id: string
          updated_at?: string
        }
        Update: {
          caption?: string | null
          content_type?: string | null
          created_at?: string
          file_name?: string | null
          id?: string
          owner_id?: string
          storage_path?: string
          trade_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "trade_attachments_trade_id_fkey"
            columns: ["trade_id"]
            isOneToOne: false
            referencedRelation: "trades"
            referencedColumns: ["id"]
          },
        ]
      }
      trade_exits: {
        Row: {
          created_at: string
          exit_price: number
          exited_at: string
          fees: number
          gross_pnl: number | null
          id: string
          net_pnl: number | null
          owner_id: string
          quantity: number
          trade_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          exit_price: number
          exited_at: string
          fees?: number
          gross_pnl?: number | null
          id?: string
          net_pnl?: number | null
          owner_id: string
          quantity: number
          trade_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          exit_price?: number
          exited_at?: string
          fees?: number
          gross_pnl?: number | null
          id?: string
          net_pnl?: number | null
          owner_id?: string
          quantity?: number
          trade_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "trade_exits_trade_id_fkey"
            columns: ["trade_id"]
            isOneToOne: false
            referencedRelation: "trades"
            referencedColumns: ["id"]
          },
        ]
      }
      trade_ideas: {
        Row: {
          created_at: string
          direction: string
          id: string
          market: string
          notes: string | null
          owner_id: string
          planned_entry: number | null
          planned_stop: number | null
          planned_target: number | null
          playbook_id: string | null
          portfolio_id: string
          status: string
          symbol: string
          taken_trade_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          direction: string
          id?: string
          market?: string
          notes?: string | null
          owner_id: string
          planned_entry?: number | null
          planned_stop?: number | null
          planned_target?: number | null
          playbook_id?: string | null
          portfolio_id: string
          status?: string
          symbol: string
          taken_trade_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          direction?: string
          id?: string
          market?: string
          notes?: string | null
          owner_id?: string
          planned_entry?: number | null
          planned_stop?: number | null
          planned_target?: number | null
          playbook_id?: string | null
          portfolio_id?: string
          status?: string
          symbol?: string
          taken_trade_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "trade_ideas_playbook_id_fkey"
            columns: ["playbook_id"]
            isOneToOne: false
            referencedRelation: "playbooks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trade_ideas_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trade_ideas_taken_trade_id_fkey"
            columns: ["taken_trade_id"]
            isOneToOne: false
            referencedRelation: "trades"
            referencedColumns: ["id"]
          },
        ]
      }
      trade_reviews: {
        Row: {
          best_decision: string | null
          created_at: string
          discipline_score: number | null
          emotional_state_after: string | null
          emotional_state_before: string | null
          emotional_state_during: string | null
          id: string
          lesson_learned: string | null
          mode: string
          owner_id: string
          plan_adherence: string | null
          trade_id: string
          updated_at: string
          worst_decision: string | null
        }
        Insert: {
          best_decision?: string | null
          created_at?: string
          discipline_score?: number | null
          emotional_state_after?: string | null
          emotional_state_before?: string | null
          emotional_state_during?: string | null
          id?: string
          lesson_learned?: string | null
          mode?: string
          owner_id: string
          plan_adherence?: string | null
          trade_id: string
          updated_at?: string
          worst_decision?: string | null
        }
        Update: {
          best_decision?: string | null
          created_at?: string
          discipline_score?: number | null
          emotional_state_after?: string | null
          emotional_state_before?: string | null
          emotional_state_during?: string | null
          id?: string
          lesson_learned?: string | null
          mode?: string
          owner_id?: string
          plan_adherence?: string | null
          trade_id?: string
          updated_at?: string
          worst_decision?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "trade_reviews_trade_id_fkey"
            columns: ["trade_id"]
            isOneToOne: true
            referencedRelation: "trades"
            referencedColumns: ["id"]
          },
        ]
      }
      trade_tags: {
        Row: {
          created_at: string
          owner_id: string
          tag_id: string
          trade_id: string
        }
        Insert: {
          created_at?: string
          owner_id: string
          tag_id: string
          trade_id: string
        }
        Update: {
          created_at?: string
          owner_id?: string
          tag_id?: string
          trade_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "trade_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trade_tags_trade_id_fkey"
            columns: ["trade_id"]
            isOneToOne: false
            referencedRelation: "trades"
            referencedColumns: ["id"]
          },
        ]
      }
      trades: {
        Row: {
          account_id: string
          calculation_version: string
          closed_at: string | null
          confidence: number | null
          created_at: string
          curated_label: string
          direction: string
          discipline_score: number | null
          entry_price: number
          exit_price: number | null
          fees: number
          gross_pnl: number | null
          holding_seconds: number | null
          id: string
          import_batch_id: string | null
          initial_risk: number | null
          is_planned: boolean
          market: string
          move_percent: number | null
          net_pnl: number | null
          notes: string | null
          opened_at: string
          outcome: string | null
          owner_id: string
          planned_r_multiple: number | null
          playbook_id: string | null
          playbook_snapshot: Json | null
          portfolio_id: string
          quantity: number
          realized_r_multiple: number | null
          session: string | null
          source: string
          source_trade_id: string | null
          spread_cost: number
          status: string
          stop_loss: number | null
          swap_funding: number
          symbol: string
          take_profit: number | null
          trade_group_id: string
          updated_at: string
        }
        Insert: {
          account_id: string
          calculation_version?: string
          closed_at?: string | null
          confidence?: number | null
          created_at?: string
          curated_label?: string
          direction: string
          discipline_score?: number | null
          entry_price: number
          exit_price?: number | null
          fees?: number
          gross_pnl?: number | null
          holding_seconds?: number | null
          id?: string
          import_batch_id?: string | null
          initial_risk?: number | null
          is_planned?: boolean
          market?: string
          move_percent?: number | null
          net_pnl?: number | null
          notes?: string | null
          opened_at: string
          outcome?: string | null
          owner_id: string
          planned_r_multiple?: number | null
          playbook_id?: string | null
          playbook_snapshot?: Json | null
          portfolio_id: string
          quantity: number
          realized_r_multiple?: number | null
          session?: string | null
          source?: string
          source_trade_id?: string | null
          spread_cost?: number
          status?: string
          stop_loss?: number | null
          swap_funding?: number
          symbol: string
          take_profit?: number | null
          trade_group_id?: string
          updated_at?: string
        }
        Update: {
          account_id?: string
          calculation_version?: string
          closed_at?: string | null
          confidence?: number | null
          created_at?: string
          curated_label?: string
          direction?: string
          discipline_score?: number | null
          entry_price?: number
          exit_price?: number | null
          fees?: number
          gross_pnl?: number | null
          holding_seconds?: number | null
          id?: string
          import_batch_id?: string | null
          initial_risk?: number | null
          is_planned?: boolean
          market?: string
          move_percent?: number | null
          net_pnl?: number | null
          notes?: string | null
          opened_at?: string
          outcome?: string | null
          owner_id?: string
          planned_r_multiple?: number | null
          playbook_id?: string | null
          playbook_snapshot?: Json | null
          portfolio_id?: string
          quantity?: number
          realized_r_multiple?: number | null
          session?: string | null
          source?: string
          source_trade_id?: string | null
          spread_cost?: number
          status?: string
          stop_loss?: number | null
          swap_funding?: number
          symbol?: string
          take_profit?: number | null
          trade_group_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "trades_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trades_import_batch_fk"
            columns: ["import_batch_id"]
            isOneToOne: false
            referencedRelation: "import_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trades_playbook_id_fkey"
            columns: ["playbook_id"]
            isOneToOne: false
            referencedRelation: "playbooks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trades_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      increment_share_view_count: {
        Args: { p_share_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
